### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by bsamadi** [meetecho/simple-whip-client#15]
This is what I get when I run make:
```
src/whip-client.c:19:10: fatal error: gst/gst.h: No such file or directory
   19 | #include <gst/gst.h>
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:11: src/whip-client.o] Error 1
```

**Comment by Arsenaldc** [comment]
Have you solved this problem? How did you solve it?

**Comment by alex-vyverman** [comment]
on ubuntu 22.04, I ran:

`apt-get install -y --no-install-recommends \
        gdb \
        git \
        build-essential \
        devscripts \
        pkg-config \
        sudo \
        libc6-dev \
        gstreamer1.0-tools \
        gstreamer1.0-nice \
        gstreamer1.0-plugins-bad \
        gstreamer1.0-plugins-ugly \
        gstreamer1.0-plugins-good \
        libglib2.0-dev \
        libgstreamer-plugins-bad1.0-dev \
        libsoup2.4-dev \
        libjson-glib-dev \
        libgstreamer1.0-dev \
        libgstreamer-plugins-base1.0-dev \
        gstreamer1.0-plugins-base \
        gstreamer1.0-libav `

like shown in the dockerfile.
Afterwards it compiled
