### ISSUE TITLE
Cjillo retrying issue

### ISSUE THREAD

**Issue by jessedewild** [meetecho/simple-whip-client#19]
I get this inside the logs when I start a WHIP client:

** (whip-client:13762): WARNING **: 12:40:24.775: Failed to GET http://192.168.68.1:1900/cjllo/rootDesc.xml: Connection terminated unexpectedly, retrying in 10 seconds

**Comment by lminiero** [comment]
Apologies for the late reply, but that sounds like an issue with that backend.
