### ISSUE TITLE
Using libsoup2 and libsoup3 in the same process is not supported

### ISSUE THREAD

**Issue by bigbean17** [meetecho/simple-whip-client#20]
Hi,

I've checked the previous post relate to this issue, it seems had been fix, but I'm still getting this error. I'm using Ubuntu 22.04, here is what I did
- install libsoup-3.0
- clone this repo
- run make
- run ./whip-client -u ... -t ... -V ...
![image](https://github.com/meetecho/simple-whip-client/assets/69971426/5f3301d1-1cbd-4093-b80b-c799b2d6379e)

Any help would be appreciated. Thank you!

**Comment by lminiero** [comment]
That's because the gstreamer you're using uses libsoup2.

**Comment by robintown** [comment]
It seems this is because gst-plugins-bad depends on libnice depends on gupnp depends on libsoup 2.4. It's all blocked on this one little merge request: https://gitlab.freedesktop.org/libnice/libnice/-/merge_requests/255

nixpkgs has [further details](https://github.com/nixos/nixpkgs/issues/371265).
