### ISSUE TITLE
(whip-client:17013): libsoup-ERROR **: 23:40:28.144: libsoup3 symbols detected. Using libsoup2 and libsoup3 in the same process is not supported. Trace/breakpoint trap (core dumped)

### ISSUE THREAD

**Issue by Avinash-Gahlowt** [meetecho/simple-whip-client#23]
After building the project I'm getting this error tried with removing libsoup3.0-dev so it says can't find libsoup-30.so.0

:~/Documents/simple-whip-client$ ./whip-client -u mywhipendpoint  -t  abc00f1442ee3e8a772fbf4875d889aa6d69ddf3b109adc048e01 -V "videotestsrc is-live=true pattern=ball ! videoconvert ! queue ! vp8enc deadline=1 ! rtpvp8pay pt=96 ssrc=2 ! queue application/x-rtp,media=video,encoding-name=VP8,payload=96"

--------------------
Simple WHIP client
------------------

WHIP endpoint:  https:///myStreamName/mywhipendpoint
Bearer Token:   jfffjiorf3423rfn98
Trickle ICE:    yes (HTTP PATCH)
Auto STUN/TURN: no
STUN server:    (none)
TURN server:    (none)
Audio pipeline: (none)
Video pipeline: videotestsrc is-live=true pattern=ball ! videoconvert ! queue ! vp8enc deadline=1 ! rtpvp8pay pt=96 ssrc=2 ! queue application/x-rtp,media=video,encoding-name=VP8,payload=96

[WHIP] Initializing the GStreamer pipeline:
webrtcbin name=sendonly bundle-policy=0    videotestsrc is-live=true pattern=ball ! videoconvert ! queue ! vp8enc deadline=1 ! rtpvp8pay pt=96 ssrc=2 ! queue application/x-rtp,media=video,encoding-name=VP8,payload=96 ! sendonly. 

Don't Know how to solve ? Need help

**Comment by lminiero** [comment]
Your GStreamer installation uses libsoup2, while our client uses libsoup3. If you want to use this cllient, you need to install a GStreamer version that depends on libsoup3 instead.

**Comment by lminiero** [comment]
As an alternative, you can try to compile a commit before #16 was merged, as before we were using libsoup2 too.
